name: 'financas_data_pipeline'
version: '1.0'
profile: 'financas_data'
config-version: 2

# Caminhos para as pastas de recursos
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

# Diretório de saída
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

# Configuração de modelos
models:
  financas_data_pipeline:
    +materialized: table  # Configuração padrão para modelos
    +persist_docs: {"relation": true, "columns": true}  # Persistir documentação

    bronze:
      +schema: "bronze"
      +tags: ["bronze"]
      +materialized: table  # Tabelas para dados crus na camada Bronze
      +persist_docs: {"relation": true}  # Documentação para tabelas na camada Bronze

    prata:
      +schema: "prata"
      +tags: ["prata"]
      +materialized: incremental  # Incremental para melhorar performance na camada Prata
      +incremental_strategy: merge  # Estratégia de atualização incremental
      +unique_key: ["data", "ativo"]  # Chave única para mesclagem incremental
      +persist_docs: {"relation": true, "columns": true}  # Persistir documentação completa

    ouro:
      +schema: "ouro"
      +tags: ["ouro"]
      +materialized: table  # Tabelas finais consolidadas na camada Ouro
      +persist_docs: {"relation": true, "columns": true}  # Persistir documentação completa
