version: 2

sources:
  - name: bronze
    description: "Camada Bronze: Dados crus coletados diretamente de APIs e outras fontes externas."
    schema: bronze
    tables:
      - name: ativos
        description: "Tabela de dados crus sobre ativos financeiros."
      - name: indicadores
        description: "Tabela de dados crus sobre indicadores técnicos."
      - name: tesouro
        description: "Tabela de dados crus sobre rendimentos do Tesouro."

  - name: prata
    description: "Camada Prata: Dados transformados, limpos e padronizados."
    schema: prata
    tables:
      - name: ativos
        description: "Tabela transformada contendo dados limpos sobre ativos financeiros."
      - name: indicadores
        description: "Tabela transformada contendo dados limpos sobre indicadores técnicos."
      - name: tesouro
        description: "Tabela transformada contendo dados limpos sobre rendimentos do Tesouro."

  - name: ouro
    description: "Camada Ouro: Dados consolidados e prontos para análise."
    schema: ouro
    tables:
      - name: portfolio
        description: "Tabela final consolidada contendo informações sobre ativos, indicadores e Tesouro."
