version: '3.8'
services:
  webserver:
    ports:
      - "8080:8080"  # Porta do Airflow
      - "8000:8000"  # Porta do DBT Docs
    build:
      context: .
    environment:
      DBT_HOST: postgres
      DBT_PORT: 5432
      DBT_USER: airflow
      DBT_ENV_SECRET_PASSWORD: airflow
      DBT_DATABASE: airflow
      DBT_SCHEMA: public
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./data:/usr/local/airflow/data
      - ./dbt:/usr/local/airflow/dbt  # Mapeia toda a pasta dbt
      - ./dbt/profiles.yml:/home/astro/.dbt/profiles.yml  # Mapeia o profiles.yml para o local esperado
  scheduler:
    build:
      context: .
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./data:/usr/local/airflow/data
      - ./dbt:/usr/local/airflow/dbt
      - ./dbt/profiles.yml:/home/astro/.dbt/profiles.yml
  worker:
    build:
      context: .
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./data:/usr/local/airflow/data
      - ./dbt:/usr/local/airflow/dbt
      - ./dbt/profiles.yml:/home/astro/.dbt/profiles.yml

volumes:
  data:
