version: 2

models:
  - name: aggregated_financial_data
    description: "Modelo que consolida os dados e calcula métricas agregadas."
    columns:
      - name: trade_date
        description: "Data consolidada."
      - name: avg_price
        description: "Preço médio das ações na data."
      - name: total_volume
        description: "Volume total de transações na data."
