name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SQLALCHEMY_WARN_20: "1"
      SQLALCHEMY_SILENCE_UBER_WARNING: "1"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Remove versões conflitantes de pandas e numpy
        python -m pip uninstall -y numpy pandas || true
        # Instalar as dependências a partir do arquivo requirements.txt
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # Lint para garantir qualidade do código
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero trata todos os erros como warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run pytest
      run: pytest tests/ --disable-warnings
